### ISSUE TITLE
Problem downloading eplets

### ISSUE THREAD

**Issue by jeffr100** [ramonamerong/hladownload#1]
I have been looking for an easy way to download a conversion table of HLA alleles to eplets and I found your website.  I tried this command and got an error.  Please let me know if you can help.  If it is easier, can you just send me a flat file of the table?

(base) jeffrey@MacBook-Pro:~/Downloads> hladownload -E

Loading HLA locus alignments...
Looking for latest IMGT/HLA database version number: 3500

Saving eplets that are present in the specified alleles to 'eplets' (this can take a while)...
Locus DRA does not support eplet output.
Locus DQA2 does not support eplet output.
Retrieving eplets from eplet registry database:
Traceback (most recent call last):
File "/Users/jeffrey/miniconda3/bin/hladownload", line 33, in <module>
sys.exit(load_entry_point('hladownload==1.0', 'console_scripts', 'hladownload')())
File "/Users/jeffrey/miniconda3/lib/python3.9/site-packages/hladownload-1.0-py3.9.egg/hladownload/__main__.py", line 137, in main
saveEplets(epletOutputFolder, alignmentObject, outputExtension, outputDelimiter, args.all_eplets, epletSupportedLoci)
File "/Users/jeffrey/miniconda3/lib/python3.9/site-packages/hladownload-1.0-py3.9.egg/hladownload/eplet.py", line 257, in saveEplets
for locusGroup, df in retrieveEplets(list(locusGroups)).items():
File "/Users/jeffrey/miniconda3/lib/python3.9/site-packages/hladownload-1.0-py3.9.egg/hladownload/eplet.py", line 80, in retrieveEplets
df.columns = inputTableHeader.values()
File "/Users/jeffrey/miniconda3/lib/python3.9/site-packages/pandas/core/generic.py", line 5588, in __setattr__
return object.__setattr__(self, name, value)
File "pandas/_libs/properties.pyx", line 70, in pandas._libs.properties.AxisProperty.__set__
File "/Users/jeffrey/miniconda3/lib/python3.9/site-packages/pandas/core/generic.py", line 769, in _set_axis
self._mgr.set_axis(axis, labels)
File "/Users/jeffrey/miniconda3/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 214, in set_axis
self._validate_set_axis(axis, new_labels)
File "/Users/jeffrey/miniconda3/lib/python3.9/site-packages/pandas/core/internals/base.py", line 69, in _validate_set_axis
raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 4 elements

**Comment by ramonamerong** [comment]
Hi jeffrey,
I was not notified of this issue until recently but this should now be fixed in the latest release.
(Retrieval of the eplets was broken as the eplet registry had updated their website).
